/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendeTusPropiedadesRouteImport } from './routes/vende-tus-propiedades'
import { Route as IndexRouteImport } from './routes/index'

const VendeTusPropiedadesRoute = VendeTusPropiedadesRouteImport.update({
  id: '/vende-tus-propiedades',
  path: '/vende-tus-propiedades',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vende-tus-propiedades': typeof VendeTusPropiedadesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vende-tus-propiedades': typeof VendeTusPropiedadesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vende-tus-propiedades': typeof VendeTusPropiedadesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/vende-tus-propiedades'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/vende-tus-propiedades'
  id: '__root__' | '/' | '/vende-tus-propiedades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VendeTusPropiedadesRoute: typeof VendeTusPropiedadesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vende-tus-propiedades': {
      id: '/vende-tus-propiedades'
      path: '/vende-tus-propiedades'
      fullPath: '/vende-tus-propiedades'
      preLoaderRoute: typeof VendeTusPropiedadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VendeTusPropiedadesRoute: VendeTusPropiedadesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
